version: '3'

services:
  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
